export const FETCH_PRODUCTOS = 'FETCH_PRODUCTOS'
export const FETCH_PRODUCTOS_LOADING = 'FETCH_PRODUCTOS_LOADING';
export const FETCH_PRODUCTOS_ERROR = 'FETCH_PRODUCTOS_ERROR';
export const SORT_PRODUCTOS = 'SORT_PRODUCTOS'


export const ADD_TO_CARRITO = 'ADD_TO_CARRITO'
export const REMOVE_FROM_CARRITO = 'REMOVE_FROM_CARRITO'
